### PR TITLE
LSTM - Stock Price Prediction

### PR DESCRIPTION
**Pull request by Volcano-Dragon**
## Description
(Write your answer here.)

## Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.

## Related Issues or Pull Requests
#104

### CODE REVIEW

**Review by khusheekapoor — CHANGES_REQUESTED** [review]
Hi, please link the notebook to the readme of the machine learning directory.

**Comment by Volcano-Dragon** [comment]
> Hi, please link the notebook to the readme of the machine learning directory.

Hello the requested changes is done now

**Review by khusheekapoor — CHANGES_REQUESTED** [review]
Hi, please link the notebook to the readme of the main ML directory.

**Comment by Volcano-Dragon** [comment]
> Hi, please link the notebook to the readme of the main ML directory.

Link added successfully to the main readme file

**Pull request closed without merging**
