### PR TITLE
GSSOC'23: Cloth Similarity Search 

### PR DESCRIPTION
**Pull request by shashank1623**
## Description
Keeping all the problems related to issue 135 in mind . I have solved the Issue of Cloth_similarity_search . Please review it and merge it . IF there is any issue in my code please guide me to improve it.

## Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.

(Add x in the [] to mark as completed.)

## Related Issues or Pull Requests
https://github.com/The-Data-Alchemists-Manipal/MindWave/issues/135
(Link the Issue Number over here.)

### CODE REVIEW

**Review by khusheekapoor — CHANGES_REQUESTED** [review]
Hi, please update the readme of the ML folder as well.

**Comment by shashank1623** [comment]
Please let me know what changes in readme.md do you want ?

**Comment by khusheekapoor** [comment]
@shashank1623 - link your notebook to the readme.

**Comment by shashank1623** [comment]
hey @khusheekapoor i have added the notebook path in the readme.md

**Review by khusheekapoor — CHANGES_REQUESTED** [review]
@shashank1623 - you have to link the notebook to the readme of the main ML folder, not the one that you have created inside the ML directory. I hope you understand :))

**Comment by shashank1623** [comment]
Done added the notebook link in the readme of the main ML folder.

**Comment by shashank1623** [comment]
Hey can you please Merge this Pr . it's been a long time .

**Comment by shashank1623** [comment]
and  please give a label of gssoc23

**Review by khusheekapoor — APPROVED** [review]

**Pull request merged**
