### PR TITLE
Support Vector Machines (SVMs) on Diabetes Dataset

### PR DESCRIPTION
**Pull request by ASHWIN492**
## Description
Here I have used SVMs to predict wither the person is diabetic or not.

## Checklist

- [] I've read the contribution guidelines.
- [] I've checked the issue list before deciding what to submit.
- [] I've edited the README.md and link to my code.

(Add x in the [] to mark as completed.)

## Related Issues or Pull Requests
(#27)

### CODE REVIEW

**Comment by ASHWIN492** [comment]
I hope this is uploaded and linked to README.md of machine learning directory. Kindly check this and let me know if there are any future changes to be done. Thank you

**Review by khusheekapoor — CHANGES_REQUESTED** [review]
The file shouldn't be named `algorithm_dataset`. It should be the algorithm and dataset that you have used. Please make the required changes.

**Comment by ASHWIN492** [comment]
hi @khusheekapoor can you review it i have changed the file name.

**Comment by ASHWIN492** [comment]
hi @theyashwanthsai I think I missed to link .

**Comment by ASHWIN492** [comment]
Hi @khusheekapoor can you look int my pull request

**Pull request merged**
