### PR TITLE
Mobile price prediction #73

### PR DESCRIPTION
**Pull request by lcs2022026**
## Description
i had made Mobile price prediction classification  #73

## Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.

(Add x in the [] to mark as completed.)

## Related Issues or Pull Requests
#73 
please kindly check and merge into main branch

### CODE REVIEW

**Review by khusheekapoor — CHANGES_REQUESTED** [review]
Hi, please link the folder to the Machine Learning directory's README.

**Comment by lcs2022026** [comment]
Its already linked in the readme and its present in machine learning directory
@khusheekapoor

**Comment by khusheekapoor** [comment]
@lcs2022026 - I cannot see it in the code preview.

**Comment by lcs2022026** [comment]
Can you check the readme to confirm, cause I had checked it 
@khusheekapoor

**Pull request merged**
