### PR TITLE
Reinforcement Learning for Autonomous Robot Navigation

### PR DESCRIPTION
**Pull request by ayush-09**
## Description
Create Reinforcement Learning for Autonomous Robot Navigation

## Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.

(Add x in the [] to mark as completed.)

## Related Issues or Pull Requests
(Link the Issue Number over here.)
#449

### CODE REVIEW

**Comment by ayush-09** [comment]
@khusheekapoor Please review the PR

**Review by khusheekapoor — CHANGES_REQUESTED** [review]
Hi, why have you deleted so many files from the readme of Data Analytics, Machine Learning, and Reinforcement Learning?

**Comment by ayush-09** [comment]
@khusheekapoor Please check and confirm me.

**Comment by khusheekapoor** [comment]
I can still not see the additions.

**Comment by ayush-09** [comment]
@khusheekapoor Now Please check

**Comment by khusheekapoor** [comment]
Still can't see, I suggest you close this PR and open a new one.

**Pull request closed without merging**
