### PR TITLE
Breast Cancer Prediction

### PR DESCRIPTION
**Pull request by ManaswiKasiraju**
## Description
Here I have created different Machine Learning models for predicting breast cancer under supervised learning. Also calculated the accuracies for each model.

## Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.

## Related Issues or Pull Requests
#67

### CODE REVIEW

**Comment by ManaswiKasiraju** [comment]
I hope this is uploaded and linked to README.md of machine learning directory. Kindly check this and let me know if there are any future changes to be done. Thank you

**Review by khusheekapoor — CHANGES_REQUESTED** [review]
Please rename the file. It shouldn't be just `algorithm_dataset.ipynb`. It should be which algorithm and dataset you have used.

**Comment by ManaswiKasiraju** [comment]
I used many algorithms for the same dataset.

**Comment by ManaswiKasiraju** [comment]
Is it okay if I name it "Breast Cancer Prediction".

**Pull request closed without merging**
