### PR TITLE
Predicting Credit Card Approvals

### PR DESCRIPTION
**Pull request by sadhana70**
## Description
It is an automatic credit card approval predictor using machine learning techniques, just like real banks do. Logistic regression is used and grid search is performed using GridSearchCV. Also, preprocessing is done using MinMaxScaler.

## Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.

(Add x in the [] to mark as completed.)

## Related Issues or Pull Requests
(Link the Issue Number over here.)
Issue number<#190>

### CODE REVIEW

**Review by khusheekapoor — CHANGES_REQUESTED** [review]
Please create a folder inside the ML directory and only link the notebook. Description is not required.

**Comment by sadhana70** [comment]
So readme file and notebook file should only be included in ML directory?

**Comment by theyashwanthsai** [comment]
@sadhana70 Please remove the description and just link the code file in readme.

**Review by khusheekapoor — CHANGES_REQUESTED** [review]
Hi, please name the file correctly. Replace the algorithm-dataset with the algorithm and dataset that you've used.

**Pull request closed without merging**
