### PR TITLE
Global Energy Statistics #247

### PR DESCRIPTION
**Pull request by Akhil-77**
## Description
I have created new repository for Time series forecasting and uploaded my project in the same repo. and I have also created the README.md file for the same.

## Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.

## Related Issues or Pull Requests
[(Issue #247)](https://github.com/The-Data-Alchemists-Manipal/MindWave/issues/247)

### CODE REVIEW

**Comment by Akhil-77** [comment]
Hey @theyashwanthsai please merge this so I can work on other projects :)

**Review by khusheekapoor — CHANGES_REQUESTED** [review]
Hi, please add the files in the appropriate folder [Data Analytics]. You can make a time series folder inside the same.

**Comment by Akhil-77** [comment]
Hey @khusheekapoor I have done the changes

**Comment by Akhil-77** [comment]
@khusheekapoor please review the changes

**Review by khusheekapoor — APPROVED** [review]

**Pull request merged**
