### PR TITLE
Brain tumor classification #114

### PR DESCRIPTION
**Pull request by lcs2022026**
## Description
I had made model for brain tumor classification #114

## Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.

(Add x in the [] to mark as completed.)

## Related Issues or Pull Requests
#114

### CODE REVIEW

**Comment by lcs2022026** [comment]
@theyashwanthsai 
kindly check the pull request and then merge into the main branch

**Comment by lcs2022026** [comment]
@theyashwanthsai @khusheekapoor 
kindly check the pull requests and then merge into the main branch

**Comment by khusheekapoor** [comment]
Please remove the images from the repository. Instead, upload them to google drive and link them in your notebook. They are making the repo too heavy.

**Review by khusheekapoor — CHANGES_REQUESTED** [review]
Hi, please link the notebook and not the dataset in the readme.

**Comment by lcs2022026** [comment]
@khusheekapoor 
I had linked the link of notebook in the readme correctly , I apologize for  doing lot of mistakes as i am still new to git ,i am still learning ,I will not repeat my mistake

**Pull request merged**
