### PR TITLE
[GSSOC'23]Movie Revenue Prediction

### PR DESCRIPTION
**Pull request by smty2018**
## Description
#371 
Added movie box office revenue model(linear regression).

## Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.

(Add x in the [] to mark as completed.)

## Related Issues or Pull Requests
#371 

Description:
I used linear regression to model the relationship between the production budget and revenue, and visualise the data through scatter plots, regression lines, and residual plots.In this project, data cleaning techniques such as handling missing values, removing duplicates, and filtering out empty or irrelevant data was applied.  The goal is to understand the impact of production budget on revenue and evaluate the accuracy of the regression model.

Models Used:
1.Linear Regression: to establish a linear relationship between the production budget and its worldwide gross revenue.
2.Residual Analysis: residuals  from the linear regression was analyzed to assess the quality of the model.
3.Influence Analysis: Cook's distance was calculated to identify influential data points.

Libraries Used:
Pandas
NumPy
Matplotlib
Seaborn
Scikit-learn
Statsmodels

Accuracy Measures:
r2 score: 0.5480572766399463
Mean Absolute Error: 63591114.52182109
Mean Squared Error: 1.377529464817386e+16
Root Mean Squared Error: 117368201.1797653

Some Imp Data Visualisations:
output(3)
download (4)
download (5)
download (6)
download (7)

### CODE REVIEW

**Comment by smty2018** [comment]
@khusheekapoor please review it and merge if no problems exists.

**Review by khusheekapoor — APPROVED** [review]
Hi, please link the folder to the readme of the ml directory.

**Review by khusheekapoor — CHANGES_REQUESTED** [review]
Hi, please link the folder to the readme of the ml directory.

**Comment by smty2018** [comment]
> Hi, please link the folder to the readme of the ml directory.

@khusheekapoor i have added the link, can you review it please and merge if no problems exist. thank you

**Pull request merged**
