### PR TITLE
GSSOC'23 : Volcanic Eruption Prediction

### PR DESCRIPTION
**Pull request by shashank1623**
## Description
As discussed in issue no #589 . this machine learning module has been  implemented using Random Forest Regressor.

## Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.

(Add x in the [] to mark as completed.)

## Related Issues or Pull Requests
(Link the Issue Number over here.)
#589

### CODE REVIEW

**Comment by shashank1623** [comment]
Please approv this pr . and give the label og GSSOC'23 with appropriate .

**Review by khusheekapoor — CHANGES_REQUESTED** [review]
Hi, please rename the untitled jupyter notebook.

**Comment by shashank1623** [comment]
Updated Please LGTM !  and give the label og GSSOC'23 with appropriate level.

**Comment by shashank1623** [comment]
@khusheekapoor Please merge this pr

**Review by khusheekapoor — APPROVED** [review]

**Pull request merged**
