### PR TITLE
Random forest smoker UnitedKingdom

### PR DESCRIPTION
**Pull request by pgs17**
## Description
From the Dataset I classified whether a person in United Kingdom is a smoker or not using Random Forest Classifier with accuracy of 75%

## Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.

(Add x in the [] to mark as completed.)

## Related Issues or Pull Requests
#51

### CODE REVIEW

**Review by khusheekapoor — CHANGES_REQUESTED** [review]
README should be linked to the notebook in the repository.

**Comment by pgs17** [comment]
I have done it u can please recheck it again

**Comment by theyashwanthsai** [comment]
@pgs17 It seems that you have added extra texts apart from the link. Please check it once

**Comment by pgs17** [comment]
@theyashwanthsai I have removed that extra space.Kindly check it

**Comment by pgs17** [comment]
@khusheekapoor U can check and tell me if further solving is required

**Pull request closed without merging**
