### PR TITLE
Deep lake is added

### PR DESCRIPTION
**Pull request by shraddha761**
## Description
(Write your answer here.)

## Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.

(Add x in the [] to mark as completed.)

## Related Issues or Pull Requests
#633

### CODE REVIEW

**Comment by shraddha761** [comment]
@Kota-Karthik can you Please review

**Comment by Kota-Karthik** [comment]
How could I review this, I am not a mentor!! @shraddha761

**Comment by shraddha761** [comment]
@Kota-Karthik Really sorry By mistakenly I mention you

**Comment by shraddha761** [comment]
@khusheekapoor Please review

**Comment by Kota-Karthik** [comment]
> @Kota-Karthik Really sorry By mistakenly I mention you

No worries @shraddha761

**Review by khusheekapoor — APPROVED** [review]

**Pull request merged**
