### PR TITLE
Added Hand-Written digit recognition to deployed projects

### PR DESCRIPTION
**Pull request by Raghucharan16**
## Description

The Hand Written Digit Recognition project is a web application that utilizes machine learning techniques to recognize and classify handwritten digits. It provides a user-friendly interface where users can draw digits on a canvas, and the application will provide real-time predictions for the digit being drawn.

## Features

- Handwritten digit recognition: The system can recognize and classify handwritten digits ranging from 0 to 9.
- Web interface: Users can draw digits on the web canvas provided by the application.
- Real-time prediction: The application provides real-time predictions as the user draws the digit.
- Clear functionality: Users can clear the canvas to start a new drawing.

## Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the README.md and link to my code.

## Related Issues or Pull Requests
[#279](https://github.com/The-Data-Alchemists-Manipal/MindWave/issues/279)

### CODE REVIEW

**Review by khusheekapoor — CHANGES_REQUESTED** [review]
Hi, please edit the readme of the labeled directory as well.

**Comment by Raghucharan16** [comment]
Hey @khusheekapoor i didn't get that what should I edit ? I mentioned readme of the project in the repo itself. Can you please explain me what is to be changed?

**Comment by khusheekapoor** [comment]
Add your project link to the readme of the deployed projects directory.

**Comment by Raghucharan16** [comment]
Thanks .Done .

**Comment by Raghucharan16** [comment]
@khusheekapoor hey what is the issue with this one, you can merge this one right? Any changes required can be discussed. Thank you for your time

**Pull request closed without merging**
