### PR TITLE
Multinomial Naive Bayes - Kaggle Spam Dataset

### PR DESCRIPTION
**Pull request by PraNavKumAr01**
## Description
Built an SMS spam classifier using Multinomial Naive Bayes and tuned the model to an accuracy score of 1.0

## Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.

(Add x in the [] to mark as completed.)

## Related Issues or Pull Requests
Issue #49

### CODE REVIEW

**Review by khusheekapoor — CHANGES_REQUESTED** [review]
Please pull the repository again and change the README file accordingly. Thanks!

**Comment by PraNavKumAr01** [comment]
I have changed the readme, is it ready to be merged now?

**Comment by PraNavKumAr01** [comment]
Let me know if any other changes have to be made?

**Review by khusheekapoor — CHANGES_REQUESTED** [review]
There are two binary files also added - what are they for?

**Review by khusheekapoor — CHANGES_REQUESTED** [review]
There are two binary files also added - what are they for?

**Comment by PraNavKumAr01** [comment]
The binary files are the model pickle file and the vectorizer pickle file that can be used to integrate into a website for the deployment of the model

**Comment by PraNavKumAr01** [comment]
Should i remove them?

**Comment by PraNavKumAr01** [comment]
is there anything else i need to do?

**Pull request closed without merging**
