### PR TITLE
Book Recommendation with collaborative filtering

### PR DESCRIPTION
**Pull request by Tisha6661**
## Description
Book data analysis and recommendations with lists of popular books, genre-based books,

## Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.

## Related Issues or Pull Requests
#396

### CODE REVIEW

**Review by khusheekapoor — CHANGES_REQUESTED** [review]
Hi, I see changes in the readmes of two directories. What is that for?

**Comment by Tisha6661** [comment]
@khusheekapoor I have done two projects, that is License Plate detection, and Book Recommendation, at beginning I didn't knew that I have to make two branches for each issue, that's they are mixed up.

**Comment by Tisha6661** [comment]
Although I have made two pull requests now, for License Plate it is #397 and for book recommendation #438

**Comment by Tisha6661** [comment]
Please merge both of these pull requests, as I have done the changes you demanded.

**Pull request merged**
