### PR TITLE
Adding Codes

### LINKED ISSUE #221: Adding New Category : Image Processing
## 💥 Proposal

Adding new codes based on Hough Transform, Morphological Transformations, Detection of Objects, Contours, etc.

### PR DESCRIPTION
**Pull request by dishamodi0910**
## Description
Adding New Category : **Image Processing**
Added some conceptual codes so one can add some image processing projects.

# Fixes #221 
## Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.

(Add x in the [] to mark as completed.)

## Related Issues or Pull Requests
(Link the Issue Number over here.)
#221

### CODE REVIEW

**Review by khusheekapoor — CHANGES_REQUESTED** [review]
Hi, please also include a README file to explain your codes.

**Review by khusheekapoor — CHANGES_REQUESTED** [review]
Hi, please make a readme for the main image processing folder as well and link your inner folder to it. You can refer the structure of the other directories for the same.

**Comment by dishamodi0910** [comment]
Hello @khusheekapoor, I have made changes and have added readme files.
Please review it once.

**Review by khusheekapoor — APPROVED** [review]
Perfect!

**Pull request merged**
